apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  strategy:
    type: {{ .Values.todoapp.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.todoapp.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      serviceAccountName: {{ .Values.todoapp.serviceAccountName.name }}
      containers:
      - name: todoapp
        image: {{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.version }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory }}
            cpu: {{ .Values.todoapp.resources.requests.cpu }}
          limits:
            memory: {{ .Values.todoapp.resources.limits.memory }}
            cpu: {{ .Values.todoapp.resources.limits.cpu }}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
{{- range $k, $v := .Values.todoapp.secrets }}
        - name: "{{ $k }}"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: "{{ $k }}"
{{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.todoapp.nodeAffinity.weight }}
              preference:
                matchExpressions:
                  - key: "{{ .Values.todoapp.nodeAffinity.key }}"
                    operator: In
                    values:
{{- range $v := .Values.todoapp.nodeAffinity.values }}
                      - "{{ $v }}"
{{- end }}
